# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 441178aa4bf4b57b6622903f7a459f72bd4470991c3ef12453c15aab563689342bece9a829e255a4f92af3e7989c404d85339a8c4f8cbf5d7971d67ed1e8458a

test:
  secret_key_base: de9219a7d6b9dd8f2b5dc9459b26ecb7d5a2e71b0b526c72ea47795d6cf8878ce616e7e928c64370bfc04e70ee1ff8cf001b2a961a9784de0435fbfc5e2cacde

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
